#! /bin/sh

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#434c5e"
bspc config active_border_color "#e5e9f0"
bspc config focused_border_color "#e5e9f0"
bspc config presel_feedback_color "#d8dee9"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap pl
#setxkbmap pl

